### PR TITLE
Adds project requirements

### PR DESCRIPTION
**Pull request by chrisbuttery**
adds `Project requirements include  Node `4.1.2` and Elm `0.16`.` to the read.me

### CODE REVIEW

**Comment by eeue56** [comment]
Could you put the requirements in a list, and requirements in a header instead of a sentence?

**Comment by chrisbuttery** [comment]
@eeue56 Sure thing!

**Comment by eeue56** [comment]
:+1: Great, thanks!

If you're looking for more places you could help out, I'm happy to point you in a direction!

**Comment by chrisbuttery** [comment]
OK Great. I'm still getting my head around Elm, but am happy to help out where I can. :+1:

**Comment by eeue56** [comment]
Awesome - I'll make a bunch of issues and label them with "help wanted". Feel free to pick any you fancy doing if you want!

**Comment by chrisbuttery** [comment]
Sounds good!

**Pull request merged**
